[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[programs.localnet]
vault = "5EpnmfjXgSvEshE8M4vv53us8n3ZfGFHTAz1eELMQ8YL"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test"
